#!/bin/bash
# .bashrc

# --------------- Source global definitions ---------------
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
# --------------- Get the system env variables ---------------
# (.profile is read by all system not only bash)
if [ -f ~/.profile ]; then
    . ~/.profile
fi

# --------------- Shell env variables ---------------
if [ -f /usr/bin/vim ]; then
    export EDITOR="/usr/bin/vim"
else
    echo -e "\e[31mThere is no vim in the system\e[0m"
fi
export DATA="/mnt/4a653e30-67ab-4d2d-8787-d4f2c3ec3742"
export DOWNLOADS="/mnt/4a653e30-67ab-4d2d-8787-d4f2c3ec3742/Downloads"
export GITHUB="$HOME/Repos/github"
export GITLAB="$HOME/Repos/gitlab"
export MY_GITHUB="$GITHUB/mzubzzz"
export MY_GITLAB="$GITLAB/mzubzzz"
export DOT="$MY_GITHUB/dotfiles"
export PROCESSTECH="$GITLAB/processtech"
export SVN="$HOME/Repos/svn"
export ADVALANGE="$GITLAB/advalange"
export WEBPMT="$ADVALANGE/webpmt"
export SCRIPTS="$DOT/scripts"
export MY_VIMRC="$HOME/.vimrc"
export GOPATH="$HOME/go"
export JAVA8="/usr/lib/jvm/java-1.8.0-amazon-corretto"
export JAVA11="/usr/lib/jvm/zulu11.74.15-ca-jdk11.0.24-linux_x64"
export JAVA11_AMAZON="/usr/lib/jvm/amazon-corretto-11.0.24.8.1-linux-x64"
export JAVA21_AMAZON="/usr/lib/jvm/amazon-corretto-21.0.4.7.1-linux-x64"
# define man pages width
export MANWIDTH=150
# variables for colorizing less pages
export LESS_TERMCAP_mb=$'\e[35m' # magenta
export LESS_TERMCAP_md=$'\e[33m' # yellow
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[34m' # blue
export LESS_TERMCAP_ue=$' # "\e[0m'
export LESS_TERMCAP_us=$'\e[4m'  # underline
export GROFF_NO_SGR=1 # For Konsole and Gnome-terminal
#increase history size
export HISTSIZE=5000
export HISTFILESIZE=10000
# avoid duplicates in history
export HISTCONTROL=ignoredups:erasedups
# append history entries
shopt -s histappend
# After each command, save and reload history
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# --------------- Path setup ---------------
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH="$HOME/Repos/github/mzubzzz/dotfiles/scripts:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
# for yarn global instalations
export PATH="$(yarn global bin):$PATH"
# Maven path For Advalange project
export PATH="/opt/apache-maven-3.8.4/bin:$PATH"
# neovim path
export PATH="$PATH:/opt/nvim-linux64/bin"
# lua language server path
export PATH="$PATH:/home/linuxbrew/.linuxbrew/Cellar/lua-language-server/3.9.3/bin"

CDPATH=".:$MY_GITHUB:$PROCESSTECH:$ADVALANGE:$MY_GITLAB"
export CDPATH


# --------------- Dircolors ---------------
if command -v dircolors &>/dev/null; then
    if [ -r "$HOME/.dircolors" ]; then
        eval "$(dircolors -b "$HOME/.dircolors")"
    else
        eval "$(dircolors -b)"
    fi
fi

# --------------- use vi-style editing interface ---------------
set -o vi

# --------------- Set ups tmux starting with new terminal ---------------
# It's good but terminal in IDE started this way.
unset PROMPT_COMMAND  # to avoid annoing '__vte_prompt_command()' error
[ -z "$TMUX" ] &&\
    { tmux attach ||\
        (exec tmux new-session &&\
    exit;)}

# --------------- Aliases ---------------
alias vi=nvim
alias iv=nvim
#alias ls="lsd -h # bad for parsing
alias ll="lsd -l"
alias maven="mvn"

# --------------- Functions ---------------
# --------------- Source completions---------------
source $DOT/completions/*
# --------------- Navigation ---------------
data() {
    cd $DATA
} && export -f data

## --------------- Custom prompt ---------------
source ~/git-prompt.sh
# export GIT_PS1_SHOWDIRTYSTATE=1 # causes slow effect in terminal
export PS1='\[\e[36m\]\u\[\e[35m\]@\[\e[31m\]\h\[\e[35m\]:\[\e[33m\]\W\[\e[32m\]$(__git_ps1 "(%s)")\[\e[35m\]$\[\e[00m\] '

# --------------- FZF completion enable ---------------
eval "$(fzf --bash)"

# ---------------- Homebrew --------------------------
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

