#!/bin/bash
# .bashrc

# --------------- Source global definitions ---------------
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
# --------------- Get the system env variables ---------------
# (.profile readed by all system not only bash)
if [ -f ~/.profile ]; then
    . ~/.profile
fi

# --------------- Shell env variables ---------------
if [ -f /usr/bin/vim ]; then
    export EDITOR="/usr/bin/vim"
else
    echo -e "\e[31mThere is no vim in the system\e[0m"
fi
export DATA="/mnt/4a653e30-67ab-4d2d-8787-d4f2c3ec3742"
export DOWNLOADS="/mnt/4a653e30-67ab-4d2d-8787-d4f2c3ec3742/Downloads"
export GITHUB="$HOME/Repos/github"
export GITLAB="$HOME/Repos/gitlab"
export MY_GITHUB="$GITHUB/mzubzzz"
export DOT="$MY_GITHUB/dotfiles"
export PROCESSTECH="$GITLAB/processtech"
export SVN="$HOME/Repos/svn"
export ADVALANGE="$GITLAB/advalange"
export SCRIPTS="$DOT/scripts"
export MYVIMRC="$HOME/.vimrc"
export GOPATH="$HOME/go"
# define man pages width
export MANWIDTH=150
# variables for colorizing less pages
export LESS_TERMCAP_mb=$'\e[35m' # magenta
export LESS_TERMCAP_md=$'\e[33m' # yellow
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[34m' # blue
export LESS_TERMCAP_ue=$' # "\e[0m'
export LESS_TERMCAP_us=$'\e[4m'  # underline
export GROFF_NO_SGR=1 # For Konsole and Gnome-terminal
# avoid duplicates in history
export HISTCONTROL=ignoredups:erasedups
# append history entries
shopt -s histappend
# After each command, save and reload history
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# --------------- Path setup ---------------
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH="$HOME/Repos/github/mzubzzz/dotfiles/scripts:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
# For Advalange project
export PATH="/opt/apache-maven-3.8.4/bin:$PATH"

CDPATH==.:$MY_GITHUB:$PROCESSTECH:$ADVALANGE
export CDPATH


# --------------- Dircolors ---------------
if command -v dircolors &>/dev/null; then
    if [ -r "$HOME/.dircolors" ]; then
        eval "$(dircolors -b "$HOME/.dircolors")"
    else
        eval "$(dircolors -b)"
    fi
fi

# --------------- use vi-style editing interface ---------------
set -o vi

# --------------- Set ups tmux starting with new terminal ---------------
# It's good but terminal in IDE started this way.
unset PROMPT_COMMAND  # to avoid annoing '__vte_prompt_command()' error
[ -z "$TMUX" ] &&\
    { tmux attach ||\
#    ((exec tmux new-session \; split-window -v \; select-pane -t 1 \;  split-window -h \; select-pane -t 3) &&\ #Will start without spliting
        (exec tmux new-session &&\
    exit;)}

# --------------- Aliases ---------------
alias vi=vim
alias ls="ls -h --color=auto"
alias ll="ls -l --color=auto"
alias copyclip="xclip -selection c" # allows copy text to the clipboard buffer

# --------------- Functions ---------------
# --------------- Navigation ---------------
data() {
    cd $DATA
} && export -f data

## --------------- Custom prompt ---------------
parse_git_branch() {
   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\e[36m\]\u\[\e[35m\]@\[\e[31m\]\h\[\e[35m\]:\[\e[33m\]\W\[\e[32m\]\$(parse_git_branch)\[\e[35m\]$\[\e[00m\] "

# --------------- FZF completion enable ---------------
FZF_COMPLETION_FILE=/usr/share/bash-completion/completions/fzf
[[ -f $FZF_COMPLETION_FILE ]] && source $FZF_COMPLETION_FILE
