#!/bin/bash

ln -sf $PWD/bashconfig $HOME/.bashrc
ls -l $HOME/.bashrc
ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc
ln -sf $PWD/profile $HOME/.profile
ls -l $HOME/.profile
ln -sf $PWD/dircolors $HOME/.dircolors
ls -l $HOME/.dircolors
ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf
ln -sf $PWD/inputrc $HOME/.inputrc
ls -l $HOME/.inputrc
