#!/bin/bash

JAVA_HOME=$JAVA21_AMAZON
echo $JAVA_HOME

cd $RTSOFT/4diac-ide && \
# /opt/apache-maven-3.9.9/bin/mvn clean package && \
/opt/apache-maven-3.9.9/bin/mvn clean verify -Dcheckstyle.skip -Dmaven.test.skip=true && \
# /opt/apache-maven-3.9.9/bin/mvn clean verify -Dcheckstyle.skip && \

figlet "STARTING FLOGIC" && \

$RTSOFT/4diac-ide/plugins/org.eclipse.fordiac.ide.product/target/products/org.eclipse.fordiac.ide.product/linux/gtk/x86_64/flogic-ide/flogic-ide -consoleLog

