#!/bin/bash

JAVA_HOME=$JAVA21_AMAZON
echo $JAVA_HOME

cd $RTSOFT/4diac-ide && \
/opt/apache-maven-3.9.9/bin/mvn clean package -Dmaven.test.skip=true && \

figlet "STARTING 4DIAC" && \
$RTSOFT/4diac-ide/plugins/org.eclipse.fordiac.ide.product/target/products/org.eclipse.fordiac.ide.product/linux/gtk/x86_64/4diac-ide/4diac-ide -consoleLog

