#!/bin/bash

JAVA_HOME=$JAVA21_AMAZON
echo $JAVA_HOME

cd $ADVALANGE/des.adv.plc/pse && \
/opt/apache-maven-3.9.9/bin/mvn clean package -Dmaven.test.skip=true && \

target_path=$ADVALANGE/des.adv.plc/pse/products/com.advalange.mopsplc.pse.product.definition/target/products/arma-plc-pse/linux/gtk/x86_64

cd $target_path/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_* &&\
chmod +x ./jre/bin/java &&\
chmod +x ./jre/lib/jspawnhelper &&\

cd $target_path/plugins/com.advalange.mopsplc.pse.matiec.linux.x86_64_1.0.0.*/ &&\
chmod -R +x matiec &&\

$target_path/pse -consoleLog



