#!/bin/bash

psql -h localhost -p 5432 -U postgres \
  -c "DROP DATABASE IF EXISTS \"runawfe\";" \
  -c "CREATE DATABASE \"runawfe\";"

if [ $? -eq 0 ]; then
    echo "✅ Database recreated successfully."
else
    echo "❌ Error: Failed to recreate database."
fi
