#!/bin/bash

psql -h localhost -p 5432 -U postgres -c "DROP DATABASE IF EXISTS \"runawfe\";"

if [ $? -eq 0 ]; then
    echo "✅ Database dropped successfully."
else
    echo "❌ Error: Failed."
fi

psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE \"runawfe\";"

if [ $? -eq 0 ]; then
    echo "✅ Database created successfully."
else
    echo "❌ Error: Failed to create database."
fi
