#!/bin/sh

ear_path=$PROCESSTECH/runawfe-professional-server/wfe-ear/'${jboss.home.dir}'/standalone/deployments/runawfe.ear
wildfly_path=~/bin/wildfly # for develop branch
# wildfly_path=~/bin/wildfly10 # for master branch
target_path=$wildfly_path/standalone/deployments/

print_success() {
    printf "++++++++++++++++++++++++++++++++++++++\n"
    printf "+++EAR has been copied \e[32mSUCCESSFULLY\e[0m+++\n"
    printf "++++++++++++++++++++++++++++++++++++++\n"
}

print_fail() {
    printf "+++++++++++++++++++++++++++++++++++++\n"
    printf "+++\e[31mFAIL\e[0m: EAR hasn't been copied +++\n"
    printf "+++++++++++++++++++++++++++++++++++++\n"
    exit 1
}

SKIP_TESTS=true
JAVA_HOME=$JAVA11_AMAZON
# JAVA_HOME=$JAVA8 # for master branch
echo $JAVA_HOME
cd $PROCESSTECH/runawfe-professional-server/wfe-app && \
# /opt/apache-maven-3.8.8/bin/mvn clean package -Dmaven.test.skip=false && \ # for master branch
mvn clean package -Dmaven.test.skip=$SKIP_TESTS && \
cp "$ear_path" "$target_path" && \
(print_success || print_fail) && \
$wildfly_path/bin/standalone.sh --debug
