#!/bin/bash

cd $PROCESSTECH/runawfe-professional-devstudio/plugins; mvn clean package &&\

$PROCESSTECH/runawfe-professional-devstudio/plugins/ru.runa.gpd.maven/target/products/RunaWFE_DeveloperStudio/linux/gtk/x86_64/runa-gpd


