#!/bin/sh

ear_path=$PROCESSTECH/runawfe-professional-server/wfe-ear/'${jboss.home.dir}'/standalone/deployments/runawfe.ear
target_path=~/bin/wildfly/standalone/deployments/

print_success() {
    printf "++++++++++++++++++++++++++++++++++++++\n"
    printf "+++EAR has been copied \e[32mSUCCESSFULLY\e[0m+++\n"
    printf "++++++++++++++++++++++++++++++++++++++\n"
}

print_fail() {
    printf "+++++++++++++++++++++++++++++++++++++\n"
    printf "+++\e[31mFAIL\e[0m: EAR hasn't been copied +++\n"
    printf "+++++++++++++++++++++++++++++++++++++\n"
    exit 1
}

JAVA_HOME=$JAVA8
cd $PROCESSTECH/runawfe-professional-server/wfe-app && \
# /opt/apache-maven-3.9.6/bin/mvn clean package -Dmaven.test.skip=false && \
mvn clean package -Dmaven.test.skip=false && \
cp "$ear_path" "$target_path" && \
(print_success || print_fail) && \
~/bin/wildfly/bin/standalone.sh --debug
