#!/bin/bash

tmux rename-window runaserver && \
tmux new-window -c $HOME -n devstudio && \
tmux new-window -c $HOME -n db && \
tmux new-window -c $PROCESSTECH/runawfe-professional-server -n gitserver && \
tmux new-window -c $PROCESSTECH/runawfe-professional-devstudio -n gitdevstudio && \
tmux new-window -c $MY_GITLAB/processtechTasks -n tasks && \
tmux new-window -c $MY_GITHUB/dotfiles -n dot && \
tmux select-window -t1
