#!/bin/bash

tmux rename-window server && \
tmux new-window -c $HOME -n DS && \
tmux new-window -c $HOME -n webEd && \
tmux new-window -c $PROCESSTECH/runawfe-professional-server/wfe-spa -n newWeb && \
tmux new-window -c $PROCESSTECH/runawfe-professional-server/wfe-spa/src -n frontNewWb && \
tmux new-window -c $PROCESSTECH/runa_web/src/main/webapp/WEB-INF -n frontWebEd && \
tmux new-window -c $HOME -n db && \
tmux new-window -c $PROCESSTECH/runawfe-professional-server -n gitServ && \
tmux new-window -c $PROCESSTECH/runawfe-professional-devstudio -n gitDS && \
tmux new-window -c $PROCESSTECH/runa_web -n gitWebEd && \
tmux new-window -c $MY_GITLAB/processtechTasks -n tasks && \
tmux new-window -c $MY_GITHUB/dotfiles -n dot && \
tmux select-window -t1
