#!/bin/bash

tmux rename-window home && \
tmux new-window -c $ADVALANGE/des.adv.plc/pse -n pse && \
tmux new-window -c $ADVALANGE/des.adv.plc/ds -n ds && \
tmux new-window -c $ADVALANGE/des.adv.plc/vd -n vd && \
tmux new-window -c $ADVALANGE/des.adv.plc/lib -n lib && \
tmux new-window -c $ADVALANGE/des.adv.plc -n git && \
tmux new-window -c $MY_GITHUB/advalangeTasks -n tasks && \
tmux select-window -t6
