#!/bin/bash
#
# set -x

URL='https://webpmt-srv01-dev.advalange.com/realms/webpmt/protocol/openid-connect/token'
USER_NAME='username=user'
PASSWORD='password=user'
GRANT_TYPE='grant_type=password'
CLIENT='client_id=webpmt'

TOKEN=$(curl $URL\
    --header 'Content-Type: application/x-www-form-urlencoded'\
    --data-urlencode $USER_NAME\
    --data-urlencode $PASSWORD\
    --data-urlencode $GRANT_TYPE\
    --data-urlencode $CLIENT\
    | jq -r '.access_token')

if [ $# -eq 1 ]
    then
        curl $1\
            -H "Authorization: Bearer "$TOKEN\
            -H "Content-Type: application/json"\
            -H "Cache-control: no-cache"\
            -H "Accept: application/json, text/plain, */*"
fi

if [ $# -eq 2 ] && [ $2 = "DELETE" ]
    then
        curl $1\
            -X $2\
            -H "Authorization: Bearer "$TOKEN\
            -H "Content-Type: application/json"\
            -H "Cache-control: no-cache"\
            -H "Accept: application/json, text/plain, */*"
    else
        curl $1\
            -X "POST"\
            -H "Authorization: Bearer "$TOKEN\
            -H "Content-Type: application/json"\
            -H "Cache-control: no-cache"\
            -H "Accept: application/json, text/plain, */*"\
            -d @$2
fi

printf "\n"


