#!/bin/bash

TOKEN=$(curl -sv 'https://webpmt-srv01-dev.advalange.com/realms/webpmt/protocol/openid-connect/token'\
    --header 'Content-Type: application/x-www-form-urlencoded'\
    --data-urlencode 'username=user'\
    --data-urlencode 'password=user'\
    --data-urlencode 'grant_type=password'\
    --data-urlencode 'client_id=webpmt'\
    | jq -r '.access_token')

if [ $# -eq 1 ]
    then
        curl $1\
            -H "Authorization: Bearer "$TOKEN\
            -H "Content-Type: application/json"\
            -H "Cache-control: no-cache"\
            -H "Accept: application/json, text/plain, */*"
fi

if [ $# -eq 2 ]
    then
        curl $1\
            -H "Authorization: Bearer "$TOKEN\
            -H "Content-Type: application/json"\
            -H "Cache-control: no-cache"\
            -H "Accept: application/json, text/plain, */*"\
            -d @$2
fi

printf "\n"


