#!/bin/bash

TOKEN=$(curl -s 'http://10.16.3.4:8180/realms/eosubp/protocol/openid-connect/token'\
    --header 'Content-Type: application/x-www-form-urlencoded'\
    --data-urlencode 'username=user'\
    --data-urlencode 'password=user'\
    --data-urlencode 'grant_type=password'\
    --data-urlencode 'client_id=eosubp-local-back'\
    | jq -r '.access_token')

curl $1\
 -H "Authorization: Bearer "$TOKEN\
 -H 'cache-control: no-cache'\
 -H "Accept: application/json, text/plain, */*"

printf "\n"


