#!bin/bash

JAVA_HOME=$JAVA11 &&\

cd $ADVALANGE/eosubp/sirius-emf-json/releng/org.eclipse.sirius.emfjson.releng &&\
mvn clean install -s ../../../settings.xml --batch-mode -DskipTests -Dcheckstyle.skip &&\

cd $ADVALANGE/eosubp/sirius-components/packages &&\
mvn clean install -s ../../settings.xml --batch-mode -DskipTests -Dcheckstyle.skip &&\

cd $ADVALANGE/eosubp/bpms-web/backend &&\
mvn clean verify -s ../../settings.xml --batch-mode -DskipTests -Dcheckstyle.skip
